require("plugins.treesitter")
require("plugins.airline")
require("plugins.autopairs")
require("plugins.colorscheme")
require("plugins.lsp")
require("plugins.nerdtree")
require("plugins.snippets")
require("plugins.telescope")
